OUTDIRR="TestSelections"
AMESSAGE="test selections"

source /opt/exp_soft/cms/t3/t3setup
mkdir /data_CMS/cms/amendola/$OUTDIRR/
mkdir $OUTDIRR
touch /data_CMS/cms/amendola/$OUTDIRR/README.txt
echo $AMESSAGE > /data_CMS/cms/amendola/$OUTDIRR/README.txt
cp /home/llr/cms/amendola/CMSSW_7_4_3/src/KLUBAnalysis/scripts/haddAll.sh /data_CMS/cms/amendola/$OUTDIRR/


#BEG=0
#END=10
#inputfilelistFolder="inputFiles/Files80X_22Giu"
#for x in $(seq $BEG $END); do
#    inputfilelist=
#    len=${#x} 
#    if [ $len -eq 1 ]; then
#	inputfilelist="$inputfilelistFolder/1_TT_files_00$x"
#    elif [ $len -eq 2 ]; then
#        inputfilelist="$inputfilelistFolder/1_TT_files_0$x"
#    elif [ $len -eq 3 ]; then
#        inputfilelist="$inputfilelistFolder/1_TT_files_$x"
#    fi
#    echo $inputfilelist
#    i=0
#    while read line; do
#	inputfiles[$i]=$line
#	echo inputfiles[$i] 
#	i=$(( $i+1 ))
#    done <$inputfilelist
#    i=$(( $i-1 ))
#    haddInput=""
#    for ii in $(seq 0 $i); do
#	haddInput="$haddInput $inputfiles"
#    done
#    echo $haddInput
#    ./scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 50 -k False -o /data_CMS/cms/amendola/$OUTDIRR/inputFiles$x   -i inputFiles/Files80X_22Giu/$inputfile
#done

inputfile='list.txt'
./scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 50 -k False -o /data_CMS/cms/amendola/$OUTDIRR/inputFiles$x   -i inputFiles/$inputfile



#python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_DY_2jet   -i inputFiles/Files80X_22Giu/3_DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1.txt    -x 6025.2 -y 0.0674381
#python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_DY_3jet   -i inputFiles/Files80X_22Giu/4_DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1.txt    -x 6025.2 -y 0.0204619
#python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_DY_4jet   -i inputFiles/Files80X_22Giu/5_DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1.txt    -x 6025.2 -y 0.0111032
#python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_DY_Bjet   -i inputFiles/Files80X_22Giu/6_DYBJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1.txt    -x 6025.2 -y 0.0141199
#python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 50 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_DY_BBjet   -i inputFiles/Files80X_22Giu/7_DYBBJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v2.txt  -x 6025.2 -y 0.00233089

#### TEST OF DY WITH ITS SF
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016_DYSFbtag.cfg  -n 200 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_DY   -i inputFiles/Files80X_22Giu/DY_allNjetAndBJet.txt              -g True -x 6025.2 


# # # ## WJets 
# # # ## NO inclusive sample + NO stitching here -- evey sample in jet binned processed exclusively with its x section
# # # ## FIXME: 1 jet still miniAOD v1
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_WJets_1jet     -i inputFiles/Files80X_22Giu/2_W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring16MiniAODv1-PUSpring16_80X_mcRun2_asymptotic_2016_v3-v1.txt            -x 11778.36381
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_WJets_2jet     -i inputFiles/Files80X_22Giu/3_W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1.txt  -x 3840.219744
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_WJets_3jet     -i inputFiles/Files80X_22Giu/4_W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1.txt  -x 1166.047866
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_WJets_4jet     -i inputFiles/Files80X_22Giu/5_W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8__RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1.txt  -x 593.055246

# # radion samples. NOTE: all samples with extended tag MC_2016_27Giu_WAndRadionSub2 are missing
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-250   -i inputFiles/Files80X_22Giu/radion_250.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-260   -i inputFiles/Files80X_22Giu/radion_260.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-270   -i inputFiles/Files80X_22Giu/radion_270.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-280   -i inputFiles/Files80X_22Giu/radion_280.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-300   -i inputFiles/Files80X_22Giu/radion_300.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-320   -i inputFiles/Files80X_22Giu/radion_320.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-340   -i inputFiles/Files80X_22Giu/radion_340.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-400   -i inputFiles/Files80X_22Giu/radion_400.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-450   -i inputFiles/Files80X_22Giu/radion_450.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-500   -i inputFiles/Files80X_22Giu/radion_500.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-550   -i inputFiles/Files80X_22Giu/radion_550.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-600   -i inputFiles/Files80X_22Giu/radion_600.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-650   -i inputFiles/Files80X_22Giu/radion_650.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-700   -i inputFiles/Files80X_22Giu/radion_700.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-750   -i inputFiles/Files80X_22Giu/radion_750.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-800   -i inputFiles/Files80X_22Giu/radion_800.txt  -x 10.0 -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_GluGluToRadionToHHTo2B2Tau_M-900   -i inputFiles/Files80X_22Giu/radion_900.txt  -x 10.0 -a True

# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_ST_tW_antitop_5f_inclusiveDecays   -i inputFiles/Files80X_22Giu/7_ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1__RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1.txt   -x 35.6
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_ST_tW_top_5f_inclusiveDecays       -i inputFiles/Files80X_22Giu/8_ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1__RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v2.txt       -x 35.6

# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_ZZTo2L2Q       -i inputFiles/Files80X_22Giu/2_ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8__RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1.txt    -x 3.22
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_WWToLNuQQ      -i inputFiles/Files80X_22Giu/3_WWTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8__RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1.txt -x 49.997
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 25 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_WZTo1L3Nu      -i inputFiles/Files80X_22Giu/5_WZTo1L3Nu_13TeV_amcatnloFXFX_madspin_pythia8__RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1.txt   -x 3.05
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 25 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_WZTo1L1Nu2Q    -i inputFiles/Files80X_22Giu/6_WZTo1L1Nu2Q_13TeV_amcatnloFXFX_madspin_pythia8__RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1.txt -x 10.71
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 100 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_WZTo2L2Q       -i inputFiles/Files80X_22Giu/4_WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8__RunIISpring16MiniAODv2-PUSpring16_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v1.txt    -x 5.595




# # ### HH
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_node_SM   -i inputFiles/Files80X_22Giu/13_GluGluToHHTo2B2Tau_node_SM_13TeV-madgraph__RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v3.txt  -x 10.0 -a True
# # python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_node_2    -i inputFiles/Files80X_22Giu/5_GluGluToHHTo2B2Tau_node_2_13TeV-madgraph__RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v3.txt  -x 10.0 -a True
# # python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_node_4    -i inputFiles/Files80X_22Giu/7_GluGluToHHTo2B2Tau_node_4_13TeV-madgraph__RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v3.txt  -x 10.0 -a True
# # python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_node_5    -i inputFiles/Files80X_22Giu/8_GluGluToHHTo2B2Tau_node_5_13TeV-madgraph__RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v3.txt  -x 10.0 -a True
# # python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_node_6    -i inputFiles/Files80X_22Giu/9_GluGluToHHTo2B2Tau_node_6_13TeV-madgraph__RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v3.txt  -x 10.0 -a True
# # python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_node_7    -i inputFiles/Files80X_22Giu/10_GluGluToHHTo2B2Tau_node_7_13TeV-madgraph__RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v3.txt  -x 10.0 -a True
# # python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_node_8    -i inputFiles/Files80X_22Giu/11_GluGluToHHTo2B2Tau_node_8_13TeV-madgraph__RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v3.txt  -x 10.0 -a True
# # python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_node_11   -i inputFiles/Files80X_22Giu/2_GluGluToHHTo2B2Tau_node_11_13TeV-madgraph__RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v3.txt  -x 10.0 -a True
# # python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_node_12   -i inputFiles/Files80X_22Giu/3_GluGluToHHTo2B2Tau_node_12_13TeV-madgraph__RunIISpring16MiniAODv2-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_miniAODv2_v0-v3.txt  -x 10.0 -a True

# # # still miniAODv1
# # python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_node_box  -i inputFiles/Files80X_22Giu/14_GluGluToHHTo2B2Tau_node_box_13TeV-madgraph__RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1.txt  -x 10.0 -a True
# # python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_node_3    -i inputFiles/Files80X_22Giu/6_GluGluToHHTo2B2Tau_node_3_13TeV-madgraph__RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1.txt  -x 10.0 -a True
# # python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_node_9    -i inputFiles/Files80X_22Giu/12_GluGluToHHTo2B2Tau_node_9_13TeV-madgraph__RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1.txt  -x 10.0 -a True
# # python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_node_10   -i inputFiles/Files80X_22Giu/1_GluGluToHHTo2B2Tau_node_10_13TeV-madgraph__RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1.txt  -x 10.0 -a True
# # python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 10 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_node_13   -i inputFiles/Files80X_22Giu/4_GluGluToHHTo2B2Tau_node_13_13TeV-madgraph__RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1.txt  -x 10.0 -a True


# ## HH with reweighting --  a lot of files!
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_0   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_0.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_0.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_1   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_1.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_1.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_2   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_2.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_2.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_3   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_3.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_3.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_4   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_4.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_4.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_5   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_5.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_5.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_6   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_6.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_6.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_7   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_7.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_7.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_8   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_8.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_8.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_9   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_9.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_9.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_10   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_10.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_10.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_11   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_11.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_11.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_12   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_12.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_12.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_13   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_13.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_13.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_14   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_14.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_14.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_15   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_15.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_15.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_16   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_16.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_16.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_17   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_17.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_17.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_18   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_18.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_18.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_19   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_19.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_19.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_20   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_20.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_20.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_21   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_21.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_21.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_22   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_22.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_22.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_23   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_23.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_23.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_24   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_24.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_24.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_25   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_25.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_25.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_26   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_26.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_26.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_27   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_27.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_27.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_28   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_28.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_28.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_29   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_29.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_29.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_30   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_30.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_30.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_31   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_31.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_31.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_32   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_32.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_32.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_33   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_33.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_33.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_34   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_34.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_34.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_35   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_35.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_35.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_36   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_36.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_36.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_37   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_37.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_37.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_38   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_38.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_38.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_39   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_39.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_39.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_40   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_40.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_40.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_41   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_41.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_41.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_42   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_42.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_42.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_43   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_43.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_43.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_44   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_44.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_44.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_45   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_45.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_45.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_46   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_46.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_46.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_47   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_47.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_47.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_48   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_48.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_48.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_49   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_49.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_49.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_50   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_50.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_50.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_lambdarew_51   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forlambda_51.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/lambdaMap_51.root -a True

# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_benchrew_0   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forbench_0.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/clusv3Map_0.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_benchrew_1   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forbench_1.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/clusv3Map_1.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_benchrew_2   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forbench_2.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/clusv3Map_2.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_benchrew_3   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forbench_3.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/clusv3Map_3.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_benchrew_4   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forbench_4.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/clusv3Map_4.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_benchrew_5   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forbench_5.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/clusv3Map_5.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_benchrew_6   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forbench_6.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/clusv3Map_6.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_benchrew_7   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forbench_7.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/clusv3Map_7.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_benchrew_8   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forbench_8.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/clusv3Map_8.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_benchrew_9   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forbench_9.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/clusv3Map_9.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_benchrew_10   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forbench_10.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/clusv3Map_10.root -a True
# python scripts/skimNtuple.py -T $OUTDIRR -s True -c  config/skim_2016.cfg  -n 5 -k False -o /data_CMS/cms/cadamuro/test_submit_to_tier3/$OUTDIRR/SKIM_HH_benchrew_11   -i inputFiles/Files80X_22Giu/lesshhV2nonresonant_forbench_11.txt  -x 10.0 -w /home/llr/cms/cadamuro/HH2016/CMSSW_7_4_7/src/KLUBAnalysis/hhReweight/clusv3Map_11.root -a True
